### PR TITLE
Disable pause

### LINKED ISSUE #39: Add task too far down on page?
Maybe work on formatting of CSS to make it all fit nicely

### LINKED ISSUE #41: Make stoping the audio more obvious
Pressing stop button stops the noise, but this is not obvious and annoying to try and figure out

### LINKED ISSUE #47: Stop button is displayed on short break and long break
It's not ideal to display a stop button during break. One idea to fix this is to disable the button and make it greyed out during the breaks.

### PR DESCRIPTION
**Pull request by ashk233**
Disabled the stop button when the timer is running. The stop button can only be used to stop the audio.
Also removed the alert so that the sound plays immediately when a session is finished. (Previously, sound only plays after the user has closed the alert that tells the user to take a break. I think this is a little redundant? Since we have the stats/task-tracking now, the user would know which session it is without the need of the alert.)

### CODE REVIEW

**Review by james-c-lars — APPROVED** [review]
These are some much  needed tweaks! I think they add a lot to the page. There was a slight bug with the reset button that I pushed a small fix for, but other than that it all looks good!

**Review by arelae — CHANGES_REQUESTED** [review]
I think there's a bug where if the user presses restart while on break, the stop button continues to be disabled during a normal pomodoro timer

**Comment by ashk233** [comment]
> I think there's a bug where if the user presses restart while on break, the stop button continues to be disabled during a normal pomodoro timer

Thanks Arela! That should be fixed now.

**Review by arelae — APPROVED** [review]
looks good

**Pull request merged**
