### PR TITLE
Feature/haleytran/stats css

### LINKED ISSUE #61: If you edit the number of pomos for a task after finishing a session for that task, it is tracked incorrectly
To replicate the bug create a task with at least two pomo sessions to complete it. Begin and finish one pomo session. If you then edit the number of pomo sessions remaining and then subsequently complete those pomo sessions, when the task is finally displayed in the stats modal as a completed task, the number of pomos taken to complete it will not be accurately reflected in the number next to it

### LINKED ISSUE #66: If you refresh the page, the number of completed pomodoros is 0 but completed tasks remain the same.
What should occur: when the page refreshes, the number of completed pomodoros should match the sum of completed tasks' pomodoros.

### LINKED ISSUE #67: Incomplete functionality for clear button in stats modal
Clear button should reset the number of pomodoros to 0 in addition to removing completed tasks. Moreover, incompleted tasks (i.e. tasks that have been started but not all of the pomodoros have been completed) will be treated the same as newly added tasks.

### PR DESCRIPTION
**Pull request by haleytran**
Stats modal now correctly deals with tasks with multiple pomodoros;clear button properly resets the modal; refreshing page retains stats modal data.

### CODE REVIEW

**Review by james-c-lars — APPROVED** [review]

**Review by james-c-lars — APPROVED** [review]
It doesn't look like the bug with changing the number of pomo sessions of a task is fixed, but the other changes look good

**Comment by haleytran** [comment]
I'm not sure why on your end the bug with changing the number of pomo sessions of a task after starting it hasn't been fixed.  I have included a video here for reference of what happens on my end. I forgot to show it in the video, but it also works when you decrease the number of pomo after starting a task.

https://user-images.githubusercontent.com/38934670/111698322-ef81dc80-87f3-11eb-9ac4-ab4cbfcfa44b.mov

**Comment by james-c-lars** [comment]
I wasn't able to replicate the bug I thought I found. Haley was definitely right about the bug being fixed.

**Review by dnanjunda — APPROVED** [review]
Looks great Haley! Thanks for getting this done.

**Pull request merged**
